description = "Google Protocol Buffers implementation in Ada"
name = "protobuf"
version = "1.1.0-git"
website = "https://github.com/reznikmm/protobuf"
authors = ["Maxim Reznik"]
executables = ["protoc-gen-ada"]
licenses = "MIT"
maintainers = ["Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/protoc_gen_ada.gpr"]
tags = ["serialization", "marshalling", "protocol", "buffers", "rpc", "generator"]

[[depends-on]]
ada_pretty = "any"
matreshka_league = "any"

[environment.PATH]
prepend = "${CRATE_ROOT}/.objs/compiler"

[build-switches]
"*".ada_version = "Ada12"
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false


# Some dependencies require precise versions during the development cycle:
[[pins]]
[pins.ada_pretty]
url    = "https://github.com/reznikmm/ada-pretty"
commit = "97c9af93b9aa1d98776357115a6986f1b2a856eb"

[pins.matreshka_league]
url    = "https://github.com/godunko/matreshka"
commit = "464d78fe7b896a24c07e0d1c91fc15ffcd7a15f6"
subdir = "packages/alire/matreshka_league"
