/* Configuration for protobuf generated by Alire */
#ifndef PROTOBUF_CONFIG_H
#define PROTOBUF_CONFIG_H

#define CRATE_VERSION "1.1.0-dev"
#define CRATE_NAME "protobuf"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
