name = "protobuf_runtime"
description = "Supporting files for Ada Protobuf implementation"
version = "2.0.0"

website = "https://github.com/reznikmm/protobuf"
authors = ["Max Reznik"]
licenses = "MIT"
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["../../gnat/protobuf_runtime.gpr"]
tags = ["serialization", "marshalling", "protocol", "buffers", "rpc", "protobuf"]

[[depends-on]]
matreshka_league = "any"

[configuration]
output_dir = "../../gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
